### ISSUE TITLE
Alternative approach to reversion?

### ISSUE THREAD

**Issue by tieguy** [ml5js/Code-of-Conduct#19]
You might simplify the reversion language by simply saying in `Code of Conduct`:

>  The condition in this section no longer applies once three years have elapsed from the date the software is made available to the public.

That would essentially leave you with Blue Oak, plus some extraneous verbiage about compliance. But even though it is more elegant, perhaps the gains from it are small since it still isn't Blue Oak per se.

**Comment by kemitchell** [comment]
I'd rather see reversion to a named license here, even if it's MIT. Naming terms > spelling out equivalent terms. It's an extra step to determine that the notice minus such-and-such section is equivalent to such-and-such other license. Especially if the notice is editing itself in operative terms. And doesn't mention the license it's transforming into.

I'm not sure lazy users, or their corporate lawyers, will expend that much effort to determine that, indeed, the license terms are now the same as a license on our green/go list.

**Comment by mwweinberg** [comment]
I am also inclined towards the clarity in explicitly naming the license.  I am sympathetic to the elegance of a self-destructing clause, but I also agree that it can make it marginally harder to understand to a casual observer.  

I have also admitted this privately before, and will do so publicly now, that the choice to revert to MIT over Blue Oak is 100% due to the frontier of my imagination while pulling together the first draft.  It turns out that frontier exists somewhere between "use Blue Oak as the model for this new license approach" (which my imagination could contemplate) and "revert to Blue Oak" (which simply did not occur to me).

Confronted with this retrospectively obvious option, I am trying to weigh the various benefits of MIT vs Blue Oak for reversion.  MIT has the advantage of what I guess one could call historical brand robustness.  To the extent that the reversion is at least partially motivated by an interest in giving comfort to people who think that this entire exercise feels a bit extreme, that can be a real value. On the other hand, if Blue Oak is good enough to be a model for the license, shouldn't it be good enough as the reversion license?

**Comment by tieguy** [comment]
I'm persuaded on explicit license naming. 

And I'm fine with MIT as a fallback; consistency with what the project has always used is a perfectly good decision criteria.

I still have Thoughts about how to handle the reversion, but I'll probably email them to Mike first to hash them out/test them a bit.
